### PR TITLE
Test against PHP7

### PR DESCRIPTION
**Pull request by WouterJ**
Let's see how this turns out :)

### CODE REVIEW

**Comment by dbu** [comment]
it looks like sonata corebundle just blew 2.3 compatibility...

for the nightly, all functional tests fail, the rest seems good.

**Comment by WouterJ** [comment]
@dbu yeah, @rande wants to support only Symfony 2.4+ for Sonata 2.4. (so, next release is a good time to support more admin backends).

**Comment by dbu** [comment]
sorry, i mistyped. its a problem with *php* 5.3 not with symfony.

**Comment by rande** [comment]
@dbu thanks to @WouterJ, the issue with php 5.3 is fixed.
@WouterJ I want to drop the support for 2.3 but as @pulzarraider states we need to keep compatibility with the LTS.

**Comment by WouterJ** [comment]
Tests are failing because of 2 errors:

* Undefined index: name in /home/travis/build/symfony-cmf/RoutingBundle/vendor/sonata-project/admin-bundle/Datagrid/Datagrid.php at line 117 [full error page: http://jsbin.com/racicokudo/1/]
* Key "parent" in object with ArrayAccess of class "Symfony\Component\Form\FormView" does not exist in SonataAdminBundle:CRUD:base_edit_form_macro.html.twig at line 21 [full error page: http://jsbin.com/racicokudo/2/]

**Comment by dbu** [comment]
i fear that for both places, sonata is using deprecated form things. maybe for 3.0, we should re-enable the deprecation warnings and look at deprecation errors in 2.7...

**Comment by WouterJ** [comment]
What do you think about merging this one and fixing the failures on the go? It'll be in allowed_failures for some months anyway

**Comment by dbu** [comment]
agreed!

**Pull request merged**
