### PR TITLE
Fix problem with reserved keywords in mysql

### PR DESCRIPTION
**Pull request by edgartebar**

### CODE REVIEW

**Comment by dbu** [comment]
ups! thanks for this fix. do i get it correctly that this is no BC breaks for postgres / sqlite users, as the column will still be called the same as before?

**Comment by edgartebar** [comment]
Doctrine suports quote strategy, i supose if doctrine suports postgres and sqlite it will work. http://doctrine-orm.readthedocs.org/en/latest/reference/basic-mapping.html#quoting-reserved-words

**Comment by lsmith77** [comment]
hmm not sure if this isn't going to bite us ... keyword quoting is quite painful. maybe better to just rename ..

**Comment by almacbe** [comment]
@lsmith77 @dbu opt you, but nowadays does not work for ORM :-P please tell us what you do prefer and we change the PR please. Thanks

**Comment by gerfigna** [comment]
+1

**Comment by dbu** [comment]
the condition mapping was only added a week ago or so, and no version tagged with it. lets change it to `condition_expr` i would say, to make peoples live easier. does that make sense @lsmith77 ?

**Comment by edgartebar** [comment]
Done, i sure that i will live easier XD thanks

**Comment by lsmith77** [comment]
+1

**Comment by dbu** [comment]
thanks a lot!

**Pull request merged**
