### PR TITLE
Test lowest versions of dependencies

### PR DESCRIPTION
**Pull request by WouterJ**
Let's see how this turns out.

I've also removed some unsupported versions and made sure the main tests are against the latest stable versions (sf 2.6 and PHP 5.6)

### CODE REVIEW

**Comment by lsmith77** [comment]
needs a rebase too

**Comment by dbu** [comment]
rebased and squashed. but we seem to still have issues with jackalope. and maybe the travis setup

**Comment by lsmith77** [comment]
why does it install symfony/testing 1.2.0 ?

**Comment by WouterJ** [comment]
@lsmith77 I think it was to prevent installing 1.1-alphaX (but I'm not sure, as the commits expaining each change have been squashed). I've now tried another solution to fix that

**Comment by lsmith77** [comment]
we need to ensure we have at least PHPCR 2.1.0-beta10
https://github.com/phpcr/phpcr/compare/2.1.0-beta9...2.1.0-beta10#diff-aa1b9fc88038bb68a683c4ffc2f4bb45R76

see
https://travis-ci.org/symfony-cmf/RoutingBundle/jobs/60933091#L251

I guess the best would be if we specify this on the jackalope/jackalope repo.
Actually we have already done this in 1.1.0 but it was not the case in https://github.com/jackalope/jackalope/blob/1.1.0-RC1/composer.json

So I guess we need to ensure that we get at least 1.1.0 stable of jackalope/jackalope

**Comment by lsmith77** [comment]
@WouterJ for now maybe better do this https://github.com/symfony-cmf/Testing/pull/101/files ?

**Comment by lsmith77** [comment]
I guess in order to leverage that we would have to release a new version and bump the minimum version of the testing component as right now its using 1.1.0 https://travis-ci.org/symfony-cmf/RoutingBundle/jobs/63945429#L181

**Comment by lsmith77** [comment]
```
$ export SYMFONY_VERSION=2.6.*
$ export PACKAGE_VERSION=high

..

PHPUnit 4.8-g49c2007 by Sebastian Bergmann and contributors.
Fatal error: Uncaught exception 'PHP_CodeCoverage_Exception' with message 'No code coverage driver available' in /home/travis/build/symfony-cmf/RoutingBundle/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:103
```

**Comment by lsmith77** [comment]
argh

```
PHP Fatal error:  Call to a member function get() on a non-object in /home/travis/build/symfony-cmf/RoutingBundle/vendor/doctrine/phpcr-bundle/Doctrine/Bundle/PHPCRBundle/OptionalCommand/ODM/RepositoryInitCommand.php on line 86
```

https://travis-ci.org/symfony-cmf/RoutingBundle/jobs/63989789#L286

**Comment by WouterJ** [comment]
We need `1.1.0-beta2` of the PHPCRBundle. Updated Testing and released 1.2.3.

**Comment by dbu** [comment]
we seem to accept a too old version of phpcr-odm:

PHP Fatal error:  Call to undefined method Doctrine\ODM\PHPCR\Translation\LocaleChooser\LocaleChooser::setFallbackLocales() in /home/travis/build/symfony-cmf/RoutingBundle/vendor/doctrine/phpcr-bundle/Doctrine/Bundle/PHPCRBundle/EventListener/LocaleListener.php on line 120

**Comment by lsmith77** [comment]
for the HHVM issue see https://github.com/liip/LiipThemeBundle/pull/126

```
-        "phpunit/phpunit": "~4.5",
+        "phpunit/phpunit": "~4.5@stable",
+        "phpunit/php-code-coverage": "@stable",
```

**Comment by lsmith77** [comment]
```
1) Symfony\Cmf\Bundle\RoutingBundle\Tests\WebTest\RedirectRouteAdminTest::testRedirectRouteEdit
Failed asserting that actual size 0 matches expected size 1.
/home/travis/build/symfony-cmf/RoutingBundle/Tests/WebTest/RedirectRouteAdminTest.php:87
/home/travis/build/symfony-cmf/RoutingBundle/Tests/WebTest/RedirectRouteAdminTest.php:48
2) Symfony\Cmf\Bundle\RoutingBundle\Tests\WebTest\RouteAdminTest::testRouteEdit
Failed asserting that actual size 0 matches expected size 1.
/home/travis/build/symfony-cmf/RoutingBundle/Tests/WebTest/RouteAdminTest.php:87
/home/travis/build/symfony-cmf/RoutingBundle/Tests/WebTest/RouteAdminTest.php:48
```

this looks like we need to adjust the functional tests there to allow for different Sonata versions

**Comment by WouterJ** [comment]
It turns out the FrontendLinkExtension wasn't compatible with SonataAdminBundle 2.2. However, it was quite easy to add support for it.

**Comment by dbu** [comment]
now everything except lowest is failing during the setup. is some of the setup not executed except for lowest?

**Comment by WouterJ** [comment]
Finally :balloon:

**Comment by dbu** [comment]
:fireworks: :tada:

**Pull request merged**
